### PR TITLE
Updates for version 0.2.0

### LINKED ISSUE #5: add SLiM dependency
```
$ conda search stdpopsim==0.1.2 --info
Loading channels: done
stdpopsim 0.1.2 py_0
--------------------
file name   : stdpopsim-0.1.2-py_0.tar.bz2
name        : stdpopsim
version     : 0.1.2
build       : py_0
build number: 0
size        : 71 KB
license     : GPLv3+
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/stdpopsim-0.1.2-py_0.tar.bz2
md5         : b34d58eba8a83e8ad4d9e796f6f1c47b
timestamp   : 2020-06-02 09:51:08 UTC
dependencies:
  - appdirs
  - attrs >=19.1.0
  - humanize
  - msprime >=0.7.1
  - pyslim >=0.401
  - python >=3.6
```

Probably not much point doing this until the next stdpopsim release, as the slim engine isn't so useful in 0.1.2.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Updates for version 0.2.0, (in favour of #7)

Updates versions following those in setup.py

Includes SLiM as a dependency, but this could be removed if necessary.

Closes #5

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@conda-forge-admin, please rerender

**Comment by jeromekelleher** [comment]
Any chance you could take a quick look over this please @grahamgower ?

I think the SLiM dep is fine for everyone except ARM mac users, but we should fix that anyway.

**Comment by jeromekelleher** [comment]
Build failing because of missing scipy dependency. Bug logged: https://github.com/popsim-consortium/stdpopsim/issues/1412

**Review by grahamgower — COMMENTED** [review]
This looks reasonable, except the zarr and pandas runtime dependencies should probably be fixed/removed upstream first.

**Comment by petrelharp** [comment]
Looks good! I agree about zarr and pandas, although if it's being tricky we could remove those at next release (which should be before too long!).

**Review by petrelharp — APPROVED** [review]

**Comment by jeromekelleher** [comment]
Should we add scipy here and get the packages working, or wait for the next release of stdpopsim without these requirements?

Note that the current pip package is broken because we don't declare the scipy dependency, so we really should get a bugfix version out ASAP.

**Comment by grahamgower** [comment]
Maybe just add scipy in here so that we're not waiting for the pip package to get fixed (which might take another day or two)?

**Comment by jeromekelleher** [comment]
Done.

**Review by grahamgower — APPROVED** [review]
LGTM!

**Pull request merged**
